CFLAGS=-Wall -g

exercise_1_1_a:
	gcc $(CFLAGS) exercise_1_1_a.c -o exercise_1_1_a

exercise_1_1_b:
	gcc $(CFLAGS) exercise_1_1_b.c -o exercise_1_1_b

exercise_1_1_c:
	gcc $(CFLAGS) exercise_1_1_c.c -o exercise_1_1_c

clean:
	rm -rf exercise_1_1_a exercise_1_1_b exercise_1_1_c
